version: "3.7"
services:
  felix:
    build:
      context: .
      dockerfile: Dockerfile-jkd8-slim
    image: ptoceti/felix-slim:latest
    container_name: felix-slim
    ports:
      - "8080:8080"
    volumes:
      - fileinstalldir:/var/felix/fileinstall
volumes:
  fileinstalldir: